const Location = [
  { name: "Abha" },
  { name: "Ad-Dilam" },
  { name: "Al-Abwa" },
  { name: "Al Artaweeiyah" },
  { name: "Al Bukayriyah" },
  { name: "Badr" },
  { name: "Baljurashi" },
  { name: "Bisha" },
  { name: "Bareg" },
  { name: "Buraydah" },
  { name: "Al Bahah" },
  { name: "Buq a" },
  { name: "Dammam" },
  { name: "Dhahran" },
  { name: "Dhurma" },
  { name: "Dahaban" },
  { name: "Diriyah" },
  { name: "Duba" },
  { name: "Dumat Al-Jandal" },
  { name: "Dawadmi" },
  { name: "Farasan" },
  { name: "Gatgat" },
  { name: "Gerrha" },
  { name: "Gurayat" },
  { name: "Al-Gwei'iyyah" },
  { name: "Hautat Sudair" },
  { name: "Habaala" },
  { name: "Hajrah" },
  { name: "Haql" },
  { name: "Al-Hareeq" },
  { name: "Harmah" },
  { name: "Ha'il" },
  { name: "Hotat Bani Tamim" },
  { name: "Hofuf" },
  { name: "Huraymila" },
  { name: "Hafr Al-Batin" },
  { name: "Jabal Umm al Ru'us" },
  { name: "Jalajil" },
  { name: "Al Jawf" },
  { name: "Jeddah" },
  { name: "Jizan" },
  { name: "Jizan Economic City" },
  { name: "Jubail" },
  { name: "Al Jafr" },
  { name: "Khafji" },
  { name: "Khaybar" },
  { name: "King Abdullah Economic City" },
  { name: "Khamis Mushayt" },
  { name: "Al-Saih" },
  { name: "Knowledge Economic City, Medina" },
  { name: "Khobar" },
  { name: "Al-Khutt" },
  { name: "Layla" },
  { name: "Lihyan" },
  { name: "Al Lith" },
  { name: "Al Majma'ah" },
  { name: "Mastoorah" },
  { name: "Al Mikhwah" },
  { name: "Al-Mubarraz" },
  { name: "Al Mawain" },
  { name: "Mecca" },
  { name: "Medina" },
  { name: "Muzahmiyya" },
  { name: "Najran" },
  { name: "Al-Namas" },
  { name: "Umluj" },
  { name: "Al-Omran" },
  { name: "Al-Oyoon" },
  { name: "Qadeimah" },
  { name: "Qatif" },
  { name: "Qaisumah" },
  { name: "Al Qunfudhah" },
  { name: "Rabigh" },
  { name: "Rafha" },
  { name: "Ar Rass" },
  { name: "Ras Tanura" },
  { name: "Riyadh" },
  { name: "Riyadh Al-Khabra" },
  { name: "Rumailah" },
  { name: "Sabt Al Alaya" },
  { name: "Sarat Abidah" },
  { name: "Saihat" },
  { name: "Safwa city" },
  { name: "Sakakah" },
  { name: "Sharurah" },
  { name: "Shaqraa" },
  { name: "Shaybah" },
  { name: "As Sulayyil" },
  { name: "Taif" },
  { name: "Tabuk" },
  { name: "Tanomah" },
  { name: "Tarout" },
  { name: "Tayma" },
  { name: "Thadiq" },
  { name: "Thuwal" },
  { name: "Thuqbah" },
  { name: "Turaif" },
  { name: "Tabarjal" },
  { name: "Udhailiyah" },
  { name: "Al-`Ula" },
  { name: "Um Al-Sahek" },
  { name: "Unaizah" },
  { name: "Uqair" },
  { name: "Uyayna" },
  { name: "Uyun AlJiwa" },
  { name: "Wadi Al-Dawasir" },
  { name: "Al Wajh" },
  { name: "Yanbu" },
  { name: "Az Zaimah" },
  { name: "Zulfi" },
];

export default Location;
